name: Merger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check syntax of index.php
        run: php -l index.php

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

      - name: Fetch production branch
        run: git fetch origin production

      - name: Set Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Push main to production forcefully
        run: |
          git checkout production
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/StefanKumarasinghe/SWE40006.git main:production --force


