- name: Checkout main branch
  uses: actions/checkout@v2
  with:
    ref: main

- name: Sync with production branch
  run: |
    git fetch origin production
    git merge production

- name: Only keep PHP files and remove others
  run: |
    find . -type f ! -name '*.php' -delete
    git add -A
    git commit -m "Keep only PHP files"

- name: Push changes to main
  run: git push origin main

- name: Merge main into production
  run: |
    git checkout production
    git merge main
    git push origin production
