name: Merger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check syntax of index.php
        run: php -l index.php

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

      - name: Push changes to main
        run: git push main

      - name: Fetch production branch
        run: git fetch origin production

      - name: Merge main into production
        run: |
          git checkout production
          git merge main
          git push origin production
